Repository Rdelia11/First-Project-Web, pull requests merged in 2018-06, with the labels that each got.

#5 first router
  first-project-web/package-lock.json
  first-project-web/package.json
  first-project-web/src/App.js
  first-project-web/src/modules/basket/basket.js
  first-project-web/src/modules/categories/categories.js
  first-project-web/src/modules/home/home.js
  first-project-web/src/modules/product/product.js
  first-project-web/src/modules/products/products.js
  first-project-web/src/modules/productview/productview.js
  first-project-web/src/modules/router/router.js
Labels: enhancement

#17 basket page v1
  first-project-web/public/bin.png
  first-project-web/src/index.css
  first-project-web/src/modules/basket/basket.js
Labels: enhancement

#18 categories: add link to a href to each category
  first-project-web/src/modules/categories/categories.js
  first-project-web/src/modules/router/router.js
Labels: enhancement

#19 basket_v1.1
  first-project-web/src/index.css
  first-project-web/src/modules/basket/basket.js
Labels: enhancement

#22 pastille-sur-panierV1 : ajout d'une pastille sur le panier (statique)
  first-project-web/src/index.css
  first-project-web/src/modules/navbar/navbar.js
Labels: help wanted

#25 basket redux
  first-project-web/src/modules/basket/basket.js
Labels: enhancement

#27 Vasi Nico
  first-project-web/src/index.css
  first-project-web/src/modules/products/products.js
  first-project-web/yarn.lock
Labels: enhancement

#30 redux system
  first-project-web/package-lock.json
  first-project-web/package.json
  first-project-web/src/index.js
  first-project-web/src/store/basket/handlers.js
  first-project-web/src/store/basket/reducer.js
  first-project-web/src/store/basket/selector.js
  first-project-web/src/store/catalog/actions.js
  first-project-web/src/store/catalog/handlers.js
  first-project-web/src/store/catalog/reducer.js
  first-project-web/src/store/catalog/selector.js
  first-project-web/src/store/product/actions.js
  first-project-web/src/store/product/handlers.js
  first-project-web/src/store/product/reducer.js
  first-project-web/src/store/product/selector.js
  first-project-web/src/store/store.js
Labels: enhancement

#32 Pastille panier liee au store
  first-project-web/src/App.js
  first-project-web/src/index.css
  first-project-web/src/modules/navbar/navbar.js
  first-project-web/src/modules/router/router.js
Labels: bug

#34 + total
  first-project-web/src/modules/basket/basket.js
  first-project-web/src/store/basket/handlers.js
  first-project-web/src/store/basket/reducer.js
Labels: enhancement

#37 All products
  first-project-web/src/index.css
  first-project-web/src/modules/categories/categories.js
Labels: enhancement

#38 filterCategory
  first-project-web/package-lock.json
  first-project-web/package.json
  first-project-web/src/modules/categories/categories.js
Labels: enhancement

#39 All products
  first-project-web/package-lock.json
  first-project-web/package.json
  first-project-web/src/index.css
  first-project-web/src/modules/categories/categories.js
Labels: enhancement

#40 Filter category
  first-project-web/src/modules/categories/categories.js
Labels: bug

#50 Fix bugs
  first-project-web/src/App.js
  first-project-web/src/index.js
  first-project-web/src/modules/basket/basket.js
  first-project-web/src/modules/products/products.js
  first-project-web/src/modules/productview/productview.js
  first-project-web/src/modules/router/router.js
Labels: bug

#57 plus de warning dans la console, arrow function qui n'a pas de return…
  first-project-web/src/modules/categories/categories.js
  first-project-web/src/modules/products/products.js
Labels: bug

#58 Local storage
  first-project-web/public/index.html
  first-project-web/src/modules/basket/basket.js
  first-project-web/src/modules/router/router.js
  first-project-web/src/store/basket/reducer.js
Labels: enhancement

#61 Update index.html
  first-project-web/public/index.html
Labels: bug

#65 Local storage
  first-project-web/public/index.html
  first-project-web/src/index.js
  first-project-web/src/modules/navbar/navbar.js
  first-project-web/src/modules/router/router.js
  first-project-web/src/store/basket/reducer.js
Labels: enhancement

#66 Develop vers Master / test Heroku
  first-project-web/.env
  first-project-web/.gitignore
  first-project-web/README.md
  first-project-web/package-lock.json
  first-project-web/package.json
  first-project-web/public/bin.png
  first-project-web/public/favicon.ico
  first-project-web/public/index.html
  first-project-web/public/manifest.json
  first-project-web/public/pictures/ic_star1@2x.png
  first-project-web/public/pictures/ic_star2@2x.png
  first-project-web/public/pictures/ic_star3@2x.png
  first-project-web/public/pictures/ic_star4@2x.png
  first-project-web/public/pictures/ic_star5@2x.png
  first-project-web/public/pictures/searchicon.png
  first-project-web/server/server.js
  first-project-web/src/App.css
  first-project-web/src/App.js
  first-project-web/src/App.test.js
  first-project-web/src/index.css
  first-project-web/src/index.js
  first-project-web/src/logo.png
  first-project-web/src/logo.svg
  first-project-web/src/modules/basket/basket.js
  first-project-web/src/modules/categories/categories.js
  first-project-web/src/modules/home/home.js
  first-project-web/src/modules/navbar/navbar.js
  first-project-web/src/modules/products/products.js
  first-project-web/src/modules/productview/productview.js
  first-project-web/src/modules/router/router.js
  first-project-web/src/registerServiceWorker.js
  first-project-web/src/store/basket/actions.js
  first-project-web/src/store/basket/handlers.js
  first-project-web/src/store/basket/reducer.js
  first-project-web/src/store/basket/selector.js
  first-project-web/src/store/store.js
  first-project-web/yarn.lock
Labels: MEP

#68 testdeployheroku
  first-project-web/package.json
Labels: MEP

#69 test MEP heroku
  first-project-web/package.json
Labels: MEP

#75 Delete yarn.lock
  yarn.lock
Labels: bug
